version: "3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KERNEL_VERSION=5.10.47
    container_name: ubuntu2404
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - debugfs:/sys/kernel/debug:rw
      - ./workspace:/workspace
    tty: true
    working_dir: /workspace
volumes:
  debugfs:
    external: true
